on: [push]
name: build
jobs:
  runhaskell:
    name: agda2scala
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8.1'
          cabal-version: '3.10.1.0'

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all
      
      - name: Run tests
        run: cabal run -- agda2scala ./test/Hello.agda
