on: [push]
name: build
jobs:
  runhaskell:
    name: Hello World
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6'
          cabal-version: '3.0'

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all
